name: Linting
on: [push, pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci

      - run: npm run lint:prettier:check

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci

      - run: npm run lint:eslint:check

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Clona todo o histórico necessário

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci

      - run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Running commitlint for pull_request"
            if [ "${{ github.event.pull_request.base.sha }}" != "0000000000000000000000000000000000000000" ]; then
              npx commitlint --from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}" --verbose
            else
              echo "Base SHA is invalid, skipping commitlint for pull_request"
            fi
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "Running commitlint for push"
            if [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
              npx commitlint --from "${{ github.event.before }}" --to "${{ github.sha }}" --verbose
            else
              echo "Before SHA is invalid, skipping commitlint for push"
            fi
          else
            echo "Unknown event: ${{ github.event_name }}"
            exit 1
          fi
